### ISSUE TITLE
Integrate a CTF Plattform

### ISSUE THREAD

**Issue by J12934** [iteratec/juicy-ctf#11]
Integrate a CTF Plattform (e.g. CTFd or FBCTF) directly.

This setup should include:

- Starting up the CTF Plattform via helm

Optional but really nice to have:

- Automatically importing the challenges into the CTF Plattform, e.g. by using `juice-shop-ctf` as a libary to create the import and then importing them directly via init container / what ever to the CTF Plattform
- Automatically submit flags to the CTF Plattform
- Automatically create users for the CTF Plattform when the create a team in the balancer / sync teams between balancer and CTF Plattform
- Proxy requests to the CTF Plattform so that both JuiceShop and ScoreBoard are able to run on the same URL

**Comment by bkimminich** [comment]
With a built-in progress tracking board across all instances and given we go with a renaming of the project, this would become kind of obsolete, right?

**Comment by J12934** [comment]
Closing as not the main project focus anymore.
If anyone is interessted in tighter integration with a CTF Framework feel free to share you use case. Might still be a cool feature!
