### ISSUE TITLE
Problem with proxing on local server

### ISSUE THREAD

**Issue by Coamoo** [iteratec/juicy-ctf#23]
Hi,
I've got a certain problem. After creation of team i can't access newly created pod (after pressing Start Hacking I return to creating new team). This issue only occures when I'm using my own config file. I changed only `secure: false` to `secure: true`, because i want to launch it on our production server. Do you know what may be the problem?

**Comment by J12934** [comment]
Yeah with `secure` set to `true` you won't be able to use it with a local proxy.
It will enforce that the cookies that the balancer needs are send via https. The https termination is expected to be handled by the loadbalancer / ingress controller or what ever you'd be running. So when proxying locally the cookie cannot be set correctly.

You can turn off secure while testing and turn it on once you have the https setup working.

**Comment by Coamoo** [comment]
Ok, i will try probably with Ingress, thanks for your help.

**Comment by J12934** [comment]
No problem 👍
Happy to help
