### ISSUE TITLE
Renaming JuicyCTF

### ISSUE THREAD

**Issue by bkimminich** [iteratec/juicy-ctf#26]
Twitter poll results for renaming JuicyCTF with the goal if disambiguation from juice-shop-ctf NPM module:

![](https://i.imgur.com/XVZW9W6.png)

Did any better ideas than "MultiJuicer" come up in the meantime?

**Comment by J12934** [comment]
Nope. MultiJuicer is still the favorite.
Haven't gotten to renaming it yet. Might have some unseen ramifications, I want to make sure to do it when I have enough time to deal with them 😅

**Comment by bkimminich** [comment]
I've renamed the project references in
* eBook: https://pwning.owasp-juice.shop/appendix/trainers.html
* Intro slides: http://bkimminich.github.io/juice-shop/#/
* New website: https://www2.owasp.org/www-project-juice-shop
